FROM fedora:30

RUN dnf -y update

RUN dnf -y install systemd

# RUN dnf -y install python3 python3-dnf python3-pip libffi-devel redhat-rpm-config python-devel openssl-devel sudo git @development-tools
# RUN pip install ansible

RUN dnf -y install python3 python3-dnf libselinux-python yum sudo git
RUN dnf -y install ansible

RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

RUN mkdir -p /etc/ansible && echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME ["/apps/fedora-centos"]

CMD ["/usr/sbin/init"]