---
sudo: required

env:
  - distribution: centos
    version: 7
  # - distribution: fedora
  #   version: 30


services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=tests/docker/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests/docker'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged --volume="${PWD}":/etc/ansible ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v -i /etc/ansible/tests/inventories /etc/ansible/tests/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v -i /etc/ansible/tests/inventories /etc/ansible/tests/test.yml'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v -i /etc/ansible/tests/inventories /etc/ansible/tests/test.yml
    | grep -q 'failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - 'sudo docker rm -f "$(cat ${container_id})"'