---

- name: load variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: "Check openjdk version is present"
  shell: "java --version | grep openjdk | awk '{print $2}' 2>&1"
  changed_when: false
  register: current_version

- debug:
    msg: "Required version = {{ openjdk_version }} and current_version = {{ current_version }}"

- block:

  - name: install openjdk
    become: yes
    become_user: root
    package:
      name: "{{ openjdk_jdk_package_name }}"
      state: present
    tags:
      - openjdk_jdk_install_package

  - name: "Validate openjdk version"
    shell: "java --version | grep openjdk | awk '{print $2}' 2>&1"
    register: jdk_ver

  - fail:
      msg: "openjdk seems not been properly installe ... aborting"
    when: jdk_ver.rc != 0

  when: 
    - current_version is succeeded
    - current_version is defined
    - current_version.stdout == "" or openjdk_version.stdout | version_compare(openjdk_version, operator='<', strict=True)