---

- name: load variables
  include_vars: "openjdk_vars.yml"

- name: "Check openjdk version is present"
  shell: "java --version | grep openjdk | awk '{print $2}' 2>&1"
  changed_when: false
  register: stdout_version

- name: set current version
  set_fact: 
    current_version: "{% if stdout_version.stdout != '' %}{{ stdout_version.stdout }}{% else %}0{% endif %}"

- debug:
    msg: "Required version = {{ openjdk.version }} and current_version = {{ current_version }}"

- block:

  - name: install openjdk
    become: yes
    become_user: root
    package:
      name: "{{ openjdk.package_name }}"
      state: present
    tags:
      - openjdk_install_package

  - name: "Validate openjdk version"
    shell: "java --version | grep openjdk | awk '{print $2}' 2>&1"
    register: jdk_ver

  - fail:
      msg: "openjdk seems not been properly installe ... aborting"
    when: jdk_ver.rc != 0

  when: 
    - current_version is version(openjdk.version, '<')