---

- name: Enable ssh login using public key
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
  # shell: sed -e 's/#PubkeyAuthentication/PubkeyAuthentication/' -e 's/#AuthorizedKeysFile/AuthorizedKeysFile/' /etc/ssh/sshd_config
  become: yes

- name: Enable ssh login using AuthorizedKeysFile
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#AuthorizedKeysFile'
    line: 'AuthorizedKeysFile'
  become: yes

- name: "Ensure SSHD is restarted"
  command: /bin/true
  notify: Restart SSHD
  when: ansible_env.USER is defined
