---

- include: setup-base.yml

- hosts: all

  roles:
    - role: common
    - role: motd
    - role: sshd
    - role: rpmfusion
    - role: bash-custom
    - role: sudoers
    - role: create_users

  tasks:
    - include: ../tasks/cleanup.yml

  handlers:
   - include: ../handlers/system.yml
   - include: ../handlers/services.yml