---
- name: load variables.
  include_vars: "node_vars.yml"

- name: check if NodeJs is installed?
  shell: node -v 2>&1 | grep -v | sed 's/v//'
  register: stdout_version
  changed_when: false
  failed_when: false
  ignore_errors: true
  args:
    warn: no

- name: set current version
  set_fact: 
    current_version: "{% if stdout_version.stdout != '' %}{{ stdout_version.stdout }}{% else %}0{% endif %}"

- debug:
    msg: "Required version = {{ nodejs.version }} and current_version = {{ current_version }}"

- block:
  - name: Import Nodesource RPM key
    rpm_key:
      key: "{{nodejs.rpm_key_url}}"
      state: present
    become: yes

  - name: Add Nodesource repositories for Node.js
    yum:
      name: "{{nodejs.url}}"
      state: present
    become: yes

  - name: Ensure Node.js and npm are installed.
    package:
      name: nodejs
      state: present
      enablerepo: 'epel,nodesource'
    become: yes

  when: 
    - current_version is version(nodejs_version, '<')
