---
- name: load variables.
  include_vars: "npm_vars.yml"

- name: Define npm_packages.
  set_fact:
    npm_packages: "{{ npm.packages | list }}"
  when: npm_packages is undefined

- name: check if NPM is installed?
  shell: npm -v 2>&1
  register: stdout_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no

- name: set current version
  set_fact: 
    current_version: "{% if stdout_version.stdout != '' %}{{ stdout_version.stdout }}{% else %}0{% endif %}"

- debug:
    msg: "Required version = {{ npm.version }} and current_version = {{ current_version }}"

- block:

  - name: Ensure npm global packages are installed.
    npm:
      name: "{{ item.name | default(item) }}"
      version: "{{ item.version | default('latest') }}"
      global: yes
      state: latest
    with_items: "{{ npm_packages }}"
    ignore_errors: yes
    become: yes

  when: 
    - current_version is version(npm.version, '<')
