---

- name: Define npm_packages.
  set_fact:
    npm_packages: "{{ npm.packages | list }}"
  when: npm_packages is undefined

- name: check if NPM is installed?
  shell: npm -v 2>&1
  register: current_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no

- debug:
    msg: "current_version={{ current_version }}"

- block:

  - name: Ensure npm global packages are installed.
    npm:
      name: "{{ item.name | default(item) }}"
      version: "{{ item.version | default('latest') }}"
      global: yes
      state: latest
    with_items: "{{ npm_packages }}"
    ignore_errors: yes
    become: yes

  when: 
    - current_version is succeeded
    - current_version is defined
    - current_version.stdout == "" or current_version.stdout | version_compare(nodejs.version, operator='<', strict=True)
