---

- name: load variables.
  include_vars: "common_vars.yml"

- name: Ansible check directory exists.
  stat:
    path: "{{playbook_dir}}/.common_packages_installed"
  register: common_packages_installed

- debug:
    msg: "common_packages_installed = {{ common_packages_installed.stat }}"

- block:

  - name: Define common_packages from common_vars
    set_fact:
      common_packages: "{{ common.packages | list }}"
    when: common_packages is undefined

  - name: Ensure common packages are installed.
    package:
      name: "{{ item }}"
      state: installed
    with_items: "{{ common_packages }}"
    become: yes

  - name: Marked as installed once
    file:
      path: "{{ playbook_dir }}/.common_packages_installed"
      state: directory
      mode: 0700
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  when: 
    - common.force_install|default(false)|bool == true or not common_packages_installed.stat.exists 
