---
- name: load variables.
  include_vars: "rpmfusion_vars.yml"

- name: install the rpmfusion repo packages
  yum: 
    name: '{{ item }}'
    state: present
  with_items: '{{rpmfusion.rpms}}'
  when: ansible_os_family == "RedHat"
  become: yes
