---

- name: Copy sudoers configuration into place.
  template:
    src: templates/sudoers.j2
    dest: /etc/sudoers.d/users
    owner: root
    group: root
    mode: 0440
    force: yes
    validate: 'visudo -cf %s'
  become: yes
