---

- name: check version of docker
  shell: docker-compose --version | sed -e 's/,//' | awk '{print $3}' 2>&1 
  register: stdout_version
  changed_when: false
  failed_when: false
  ignore_errors: true
  args:
    warn: no
  become: yes

- name: set current version
  set_fact: 
    current_version: "{% if stdout_version.stdout != '' %}{{ stdout_version.stdout }}{% else %}0{% endif %}"

- debug:
    msg: "Required version = {{ docker_compose.version }} and current_version = {{ current_version }}"

- block:

  - name: Ensure pre-requisite packages are installed for docker_compose.
    package:
      name: '{{ item }}'
      state: present
    become: yes
    with_items:
      - epel-release
      - python-pip
      - docker-compose

  when: 
    - current_version is version(docker_compose.version, '<')