---

- name: Create Docker group
  group:
    name: docker
    state: present
  become: yes

- block:

  - name: Add current user to Docker group
    user:
      name: "{{ ansible_env.USER }}"
      groups: docker
      append: yes
    become: yes

  when: ansible_env.USER is defined
