---

- name: load variables.
  include_vars: "docker_vars.yml"

# Setup/install tasks.
- include: setup-docker.yml
- include: setup-docker-compose.yml
- include: setup-docker-group.yml

- name: "Ensure Docker is restarted"
  command: /bin/true
  notify: Restart Docker
  when: ansible_env.USER is defined
